### ISSUE TITLE
[Feature Request] fuzzy scoring and sort function

### ISSUE THREAD

**Issue by cireu** [jcs090218/company-fuzzy#1]
Currently `company-fuzzy` doesn't have a fuzzy sorting function(at least I can't find it in source). Would you like to add a fuzzy sorting function?

There's an elisp fuzzy scoring package [flx](https://github.com/lewang/flx) and there's [company-flx](https://github.com/lewang/flx). You can also have a look at my [fuz.el](https://github.com/cireu/fuz.el), a fuzzy scoring function powered by Rust.

**Comment by jcs090218** [comment]
Thanks for asking for this feature! I am currently thinking sorting in the alphabetic order. I don't know anything about [flx](https://github.com/lewang/flx). And base on [company-flx](https://github.com/lewang/flx)'s issue page, they have performance issue using it? :P [fuz.el](https://github.com/cireu/fuz.el) sounds good to me, but I don't prefer using external program if necessary but I might implemented as an option so the user can choose what `fuzzy backend` to use! Anyway, feel free to PR if you interested implement your [fuz.el](https://github.com/cireu/fuz.el) to this package.

**Comment by cireu** [comment]
I think flx is effcient enough to do the scoring since company won't work on a
so long candiate at most time (Don't like helm or ivy).

> Anyway, feel free to PR if you interested implement your fuz.el to this
> package.

Maybe I can do that after I publish fuz.el to melpa.

**Comment by jcs090218** [comment]
I just added `company-fuzzy-sorting-backend` variable, so you can implemented your own scoring system within the function `company-fuzzy--sort-candidates` here on [L98](https://github.com/jcs090218/company-fuzzy/blob/48a239f998ef32a7d717afdfbcea1dbc95319188/company-fuzzy.el#L98).

**Comment by jcs090218** [comment]
Now this plugin supports ` flx`'s scoring engine, I will close this issue now!

**Comment by cireu** [comment]
On Tue, 06 Aug 2019 11:41:05 +0800,
Jen-Chieh Shen wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (7bit)>]
> Now this plugin supports flx's scoring engine, I will close this issue now!
> 
> ―
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Good, flx is also a good option, I'll create a standalone package if I want to
use it with fuz.

**Comment by jcs090218** [comment]
I like your package though! [fuz.el](https://github.com/cireu/fuz.el) isn't on melpa yet. I might implement this package after this package is on melpa! :D

**Comment by jcs090218** [comment]
@cireu Just implemented this feature in #20.

Let me know if this is the correct implementation! Thanks!
